name: PROD - Terraform Apply

on:
  push:
    tags:
      - 'v*.*.*'
    paths:
      - 'envs/prod/**/*'
      - '*.tf'
      - '.github/workflows/deploy-prod.yml'
  workflow_dispatch:

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME_PROD }}
  WORKING_DIR: "."
  TF_CLI_ARGS_init: '-backend-config=envs/prod/state.config'
  TF_CLI_ARGS_plan: '-var-file=envs/prod/terraform.tfvars'
  TF_CLI_ARGS_apply: '-var-file=envs/prod/terraform.tfvars'

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  apply:
    name: Terraform apply
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v2
        id: github-app-token
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Checkout source
        uses: actions/checkout@v5
        with:
          fetch-depth: 3
          ref: ${{ github.head_ref }}
          token: ${{ steps.github-app-token.outputs.token }}
          persist-credentials: false

      - name: Configure AWS Credentials for DEV
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_DEV }}
          role-session-name: gh-actions
          aws-region: ${{ env.AWS_REGION }}

      - name: Decrypt secrets in config folder
        uses: c0x12c/gh-actions-git-secret-protector@v1.1
        with:
          filter: app-dev

      - name: Run Terraform Apply
        uses: c0x12c/gh-actions-terraform-workflows/actions/terraform-apply@v1
        env:
          TF_CLI_ARGS_init: ${{ env.TF_CLI_ARGS_init }}
          TF_CLI_ARGS_plan: ${{ env.TF_CLI_ARGS_plan }}
          TF_CLI_ARGS_apply: ${{ env.TF_CLI_ARGS_apply }}
        with:
          aws_region: ${{ env.AWS_REGION }}
          aws_role: ${{ env.AWS_ROLE_TO_ASSUME }}
          environment: prod
          python_version: '3.12'
          secret_filter: 'app-prod'
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          terraform_version: '1.10.5'
          working_dir: ${{ env.WORKING_DIR }}
